exclude: "docs|node_modules|migrations|.git|.tox|static|.md|admin.py"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: __init__.py # Excluded to work with the existing code base.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        files: (^|/).+\.(py|html|sh|css|scss|js)$
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8